# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/KiranBK18/DevOpsProject/blob/main/app.yaml'
    targetRevision: HEAD
    path: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
